(function(){
  'use strict';
  const VERSION='2.1.1';
  const STORAGE_KEY='kenc.project.autosave.v3';
  const AUTOSAVE_INTERVAL=5000;
  let lastSignature='';
  function toast(msg,error=false){let n=document.getElementById('kencProjectToast');if(!n){n=document.createElement('div');n.id='kencProjectToast';document.body.appendChild(n);}n.textContent=msg;n.className=error?'is-error':'is-ok';clearTimeout(n._t);n._t=setTimeout(()=>n.className='',2600);}
  function isDrawingActive(){return document.getElementById('drawingPanel')?.classList.contains('active')===true;}
  function signature(state){try{return JSON.stringify({cabinet:state?.activeCabinetId,cabinets:(state?.cabinets||[]).map(c=>[c.width,c.height,c.depth,(c.objects||[]).map(o=>[o.id,o.uuid,o.type,o.option,o.surface,o.x,o.y,o.w,o.h,o.rot])])});}catch(_){return String(Date.now());}}
  function saveAutosave(statusEl){const api=window.KENC_DRAWING_API,state=api?.getState?.();if(!state)return;const sig=signature(state);if(sig===lastSignature)return;try{const pack=window.KENC_PROJECT_ENGINE?.packageProject?.(state);if(!pack)return;localStorage.setItem(STORAGE_KEY,JSON.stringify(pack));lastSignature=sig;if(statusEl)statusEl.textContent=`자동저장 · ${new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`;}catch(err){if(statusEl)statusEl.textContent='자동저장 실패';}}
  function restoreAutosave(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw){toast('복구할 자동저장본이 없습니다.',true);return;}try{window.KENC_PROJECT_HISTORY?.create?.('자동저장 복구 직전','pre-autosave-restore');window.KENC_PROJECT_ENGINE.applyPackage(JSON.parse(raw));toast('최근 자동저장본을 복구했습니다.');}catch(err){toast('자동저장본 복구 실패: '+err.message,true);}}
  function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));}
  function mount(){
    if(document.getElementById('kencProjectToolbar'))return;
    const bar=document.createElement('aside');bar.id='kencProjectToolbar';bar.className='is-collapsed';
    bar.innerHTML=`<button type="button" class="kenc-project-handle" data-kenc-project="toggle" aria-expanded="false" aria-controls="kencProjectToolsBody"><span>프로젝트</span><b>⌁</b></button><div id="kencProjectToolsBody" class="kenc-project-tools-body"><header><strong>KENC 2.0 프로젝트</strong><button type="button" data-kenc-project="close" aria-label="프로젝트 도구 닫기">×</button></header><div class="kenc-project-tabs"><button class="is-active" data-kenc-tab="file">파일</button><button data-kenc-tab="history">버전 기록</button></div><section data-kenc-pane="file"><div class="kenc-project-actions"><button type="button" data-kenc-project="save">프로젝트 저장</button><button type="button" data-kenc-project="open">프로젝트 열기</button><button type="button" data-kenc-project="snapshot">스냅샷 저장</button><button type="button" data-kenc-project="restore">자동저장 복구</button></div><span data-kenc-project-status>Schema 3 · 준비</span><div class="kenc-import-preview" data-kenc-import-preview hidden></div></section><section data-kenc-pane="history" hidden><div class="kenc-history-toolbar"><button type="button" data-kenc-project="snapshot">현재 버전 저장</button><button type="button" data-kenc-project="clear-history">전체 삭제</button></div><div class="kenc-history-list" data-kenc-history-list></div><div class="kenc-diff-panel" data-kenc-diff-panel hidden></div></section><input hidden type="file" accept=".kenc,application/json" data-kenc-project-file></div>`;
    document.body.appendChild(bar);
    const file=bar.querySelector('[data-kenc-project-file]'),status=bar.querySelector('[data-kenc-project-status]'),handle=bar.querySelector('.kenc-project-handle'),historyList=bar.querySelector('[data-kenc-history-list]'),importPreview=bar.querySelector('[data-kenc-import-preview]');let pendingImport=null;
    const setOpen=open=>{bar.classList.toggle('is-collapsed',!open);handle.setAttribute('aria-expanded',String(open));};
    const syncVisibility=()=>{const visible=isDrawingActive();bar.classList.toggle('is-page-hidden',!visible);if(!visible)setOpen(false);};
    const showTab=name=>{bar.querySelectorAll('[data-kenc-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.kencTab===name));bar.querySelectorAll('[data-kenc-pane]').forEach(p=>p.hidden=p.dataset.kencPane!==name);if(name==='history')renderHistory();};
    function renderHistory(){const items=window.KENC_PROJECT_HISTORY?.list?.()||[];if(!items.length){historyList.innerHTML='<p class="kenc-history-empty">저장된 버전 기록이 없습니다.</p>';return;}historyList.innerHTML=items.map(item=>{const d=new Date(item.createdAt);const cmp=window.KENC_PROJECT_HISTORY.compare(item.id);const delta=cmp?`현재 대비 객체 ${cmp.objectDelta>=0?'+':''}${cmp.objectDelta}`:'';return `<article class="kenc-history-item"><div><strong>${escapeHtml(item.label)}</strong><small>${d.toLocaleString('ko-KR')} · 함체 ${item.summary.cabinetCount} · 객체 ${item.summary.objectCount}</small><em>${escapeHtml(delta)}</em></div><div><button data-kenc-history="compare" data-id="${item.id}">비교</button><button data-kenc-history="restore" data-id="${item.id}">전체 복원</button><button data-kenc-history="delete" data-id="${item.id}">삭제</button></div></article>`;}).join('');}

    function renderDiff(id){
      const panel=bar.querySelector('[data-kenc-diff-panel]'),diff=window.KENC_PROJECT_DIFF?.compareHistory?.(id);if(!panel||!diff){toast('비교할 수 없습니다.',true);return;}
      panel.hidden=false;panel.dataset.historyId=id;
      const sum=diff.summary;
      panel.innerHTML=`<div class="kenc-diff-head"><strong>변경 비교</strong><button type="button" data-kenc-diff="close">×</button></div><div class="kenc-diff-summary"><span>추가 ${sum.added}</span><span>삭제 ${sum.removed}</span><span>변경 ${sum.changed}</span></div>${diff.cabinets.map(c=>`<article class="kenc-diff-cabinet"><header><b>${escapeHtml(c.label)}</b><small>+${c.added.length} / -${c.removed.length} / 변경 ${c.changed.length}</small></header><button type="button" data-kenc-diff="restore-cabinet" data-cabinet-id="${escapeHtml(c.cabinetId)}">이 함체만 복원</button>${[...c.added.map(x=>['추가',x]),...c.removed.map(x=>['삭제',x]),...c.changed.map(x=>['변경',x])].slice(0,20).map(([kind,x])=>`<div class="kenc-diff-row"><span class="is-${kind==='추가'?'add':kind==='삭제'?'remove':'change'}">${kind}</span><em>${escapeHtml(x.label)}</em><button type="button" data-kenc-diff="restore-object" data-cabinet-id="${escapeHtml(c.cabinetId)}" data-object-id="${escapeHtml(x.objectId)}">객체 복원</button></div>`).join('')}</article>`).join('')}`;
    }

    async function awaitImport(prepared){await window.KENC_PROJECT_ENGINE.openFile(null,prepared);toast('호환성 검사를 통과한 프로젝트를 불러왔습니다.');saveAutosave(status);}
    function showImportPreview(prepared){const r=prepared.report,c=window.KENC_PROJECT_COMPATIBILITY?.compareCurrent?.(prepared.package);pendingImport=prepared;importPreview.hidden=false;importPreview.innerHTML=`<strong>가져오기 사전 검사</strong><small>${escapeHtml(prepared.file?.name||'프로젝트')} · Schema ${r.schema} → 3</small><div class="kenc-import-stats"><span>함체 ${r.cabinetCount}</span><span>객체 ${r.objectCount}</span><span>${r.repairs.length?'자동복구 '+r.repairs.length:'변환 없음'}</span></div>${c?`<p>현재 대비 함체 ${c.cabinetDelta>=0?'+':''}${c.cabinetDelta}, 객체 ${c.objectDelta>=0?'+':''}${c.objectDelta}</p>`:''}${r.warnings.length?`<ul>${r.warnings.slice(0,6).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:'<p class="is-ok">호환성 문제가 발견되지 않았습니다.</p>'}<div><button type="button" data-kenc-import="confirm">검사 후 열기</button><button type="button" data-kenc-import="cancel">취소</button></div>`;}

    bar.addEventListener('click',async e=>{
      const diffBtn=e.target.closest('[data-kenc-diff]');if(diffBtn){const panel=bar.querySelector('[data-kenc-diff-panel]'),act=diffBtn.dataset.kencDiff;try{if(act==='close'){panel.hidden=true;}else if(act==='restore-cabinet'){window.KENC_PROJECT_DIFF.restoreCabinet(panel.dataset.historyId,diffBtn.dataset.cabinetId);toast('선택한 함체만 복원했습니다.');renderDiff(panel.dataset.historyId);}else if(act==='restore-object'){window.KENC_PROJECT_DIFF.restoreObject(panel.dataset.historyId,diffBtn.dataset.cabinetId,diffBtn.dataset.objectId);toast('선택한 객체를 복원했습니다.');renderDiff(panel.dataset.historyId);}}catch(err){toast(err.message,true);}return;}
      const tab=e.target.closest('[data-kenc-tab]');if(tab){showTab(tab.dataset.kencTab);return;}
      const hist=e.target.closest('[data-kenc-history]');if(hist){try{if(hist.dataset.kencHistory==='restore'){window.KENC_PROJECT_HISTORY.restore(hist.dataset.id);toast('선택한 버전으로 전체 복원했습니다.');}else if(hist.dataset.kencHistory==='compare'){renderDiff(hist.dataset.id);}else window.KENC_PROJECT_HISTORY.remove(hist.dataset.id);renderHistory();}catch(err){toast(err.message,true);}return;}
      const importBtn=e.target.closest('[data-kenc-import]');if(importBtn){const act=importBtn.dataset.kencImport;if(act==='cancel'){pendingImport=null;importPreview.hidden=true;file.value='';}else if(act==='confirm'){try{if(!pendingImport)throw new Error('준비된 프로젝트가 없습니다.');window.KENC_PROJECT_HISTORY?.create?.('프로젝트 열기 직전','pre-import');awaitImport(pendingImport);pendingImport=null;importPreview.hidden=true;file.value='';}catch(err){toast(err.message,true);}}return;}
      const action=e.target?.closest?.('[data-kenc-project]')?.dataset?.kencProject;if(!action)return;
      try{if(action==='toggle')setOpen(bar.classList.contains('is-collapsed'));else if(action==='close')setOpen(false);else if(action==='save'){window.KENC_PROJECT_ENGINE.download();toast('KENC 프로젝트를 저장했습니다.');}else if(action==='open')file.click();else if(action==='snapshot'){const item=window.KENC_PROJECT_HISTORY.create('수동 스냅샷','manual');toast(`버전 저장 완료 · 객체 ${item.summary.objectCount}개`);renderHistory();}else if(action==='restore')restoreAutosave();else if(action==='clear-history'){if(confirm('저장된 버전 기록을 모두 삭제할까요?')){window.KENC_PROJECT_HISTORY.clear();renderHistory();}}}catch(err){toast(err.message,true);}
    });
    file.addEventListener('change',async()=>{if(!file.files?.[0])return;try{status.textContent='프로젝트 호환성 검사 중…';const prepared=await window.KENC_PROJECT_COMPATIBILITY.prepareFile(file.files[0]);if(!prepared.report.ok)throw new Error(prepared.report.errors.join(' '));showImportPreview(prepared);status.textContent=`Schema ${prepared.report.schema} 검사 완료 · 객체 ${prepared.report.objectCount}개`;}catch(err){pendingImport=null;importPreview.hidden=true;file.value='';status.textContent='프로젝트 검사 실패';toast(err.message,true);}});
    const boot=()=>{const s=window.KENC_DRAWING_API?.getState?.();if(s){window.KENC_PROJECT_ENGINE.normalizeState(s);status.textContent=`Schema 3 · 함체 ${s.cabinets?.length||0}개`;lastSignature=signature(s);}};
    if(window.KENC_DRAWING_API)boot();else document.addEventListener('kenc:drawing-api-ready',boot,{once:true});
    document.addEventListener('kenc:history-changed',renderHistory);new MutationObserver(syncVisibility).observe(document.getElementById('drawingPanel'),{attributes:true,attributeFilter:['class']});window.addEventListener('hashchange',syncVisibility);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveAutosave(status);});window.addEventListener('beforeunload',()=>saveAutosave(status));setInterval(()=>{if(isDrawingActive())saveAutosave(status);},AUTOSAVE_INTERVAL);syncVisibility();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
