(function(){
'use strict';
const V='1.0.6';
const mat={steel:{kind:'powder-coated-steel',color:'#d8d9d5',roughness:.72,metalness:.25},chrome:{kind:'brushed-chrome',color:'#c8ccd0',roughness:.35,metalness:.82},blackAbs:{kind:'black-abs',color:'#17191c',roughness:.68,metalness:.04},copper:{kind:'copper',color:'#b87333',roughness:.42,metalness:.82},zinc:{kind:'zinc-plated-steel',color:'#b9bec3',roughness:.48,metalness:.68},pvc:{kind:'pvc',color:'#d9dbd8',roughness:.82,metalness:0},bakelite:{kind:'bakelite',color:'#d3a326',roughness:.74,metalness:0},acrylic:{kind:'clear-acrylic',color:'#dbeef7',roughness:.16,metalness:0,opacity:.38,transparent:true}};
const lib={
 vent:{wide_louver:{label:'와이드 절곡 루버형',size:{w:160,h:90,d:16},material:mat.steel,geometry:{kind:'bent-louver',bladeCount:5,bladeAngle:38,lip:8,frame:false,integralPanel:true}}},
 anchor:{anchor_14:{label:'앙카구멍 Ø14',size:{w:14,h:14,d:1.6},geometry:{kind:'through-hole',shape:'circle',diameter:14,chamfer:.6}},screw_6:{label:'피스구멍 Ø6',size:{w:6,h:6,d:1.6},geometry:{kind:'through-hole',shape:'circle',diameter:6,chamfer:.35}}},
 key:{detach:{label:'탈착키',size:{w:28,h:34,d:7},material:mat.blackAbs,geometry:{kind:'recess-lock',shape:'square',keySlot:true}},push_button:{label:'푸쉬버튼키',size:{w:42,h:120,d:9},material:mat.chrome,geometry:{kind:'flush-swing-handle',button:true,keyCylinder:true,recess:true}},push_handle:{label:'푸쉬핸들키',size:{w:46,h:122,d:12},material:mat.chrome,geometry:{kind:'flush-paddle-handle',gripRecess:true,pushPad:true,keyCylinder:true}}},
 nameplate:{communication_100x30:{label:'통신용 명판',size:{w:100,h:30,d:1.5},material:{kind:'white-abs',color:'#f2f1ea',roughness:.72,metalness:0},geometry:{kind:'rounded-plate',radius:1}},distribution_150x30:{label:'분전반용 명판',size:{w:150,h:30,d:1.5},material:{kind:'white-abs',color:'#f2f1ea',roughness:.72,metalness:0},geometry:{kind:'rounded-plate',radius:1}}},
 acrylicWindow:{framed_clear:{label:'투명아크릴창',size:{w:220,h:140,d:7},material:mat.acrylic,geometry:{kind:'framed-window',frameWidth:7,cutout:true,panelThickness:3}}},
 emboss:{round_knockout:{label:'엠보타공 원형',geometry:{kind:'knockout',shape:'circle',score:'partial',embossDepth:1.2}},square_knockout:{label:'엠보타공 사각',geometry:{kind:'knockout',shape:'rounded-square',score:'partial',embossDepth:1.2,cornerRadius:3}}},
 cut:{round:{label:'원형타공',geometry:{kind:'through-hole',shape:'circle',chamfer:.7,ambientOcclusion:true},exportMark:{stroke:'#d72626',shape:'circle',cross:true}},square:{label:'사각타공',geometry:{kind:'through-hole',shape:'square',chamfer:.7,ambientOcclusion:true},exportMark:{stroke:'#d72626',shape:'square',cross:true}}},
 plate:{pvc_perforated:{label:'PVC속판',size:{d:5},material:mat.pvc,geometry:{kind:'backplate',perforation:'micro-round-grid',cornerSlots:4,centerHole:1,standoff:18}},steel_plain:{label:'철속판',size:{d:1.6},material:mat.steel,geometry:{kind:'backplate',perforation:'none',cornerSlots:4,standoff:18}},bakelite_yellow:{label:'베크라이트 절연판(빼끄판)',size:{d:6},material:mat.bakelite,geometry:{kind:'backplate',perforation:'none',cornerSlots:4,standoff:18}}},
 groundBar:{copper_left:{label:'동접지 좌측면',material:mat.copper,geometry:{kind:'ground-bar',side:'left',terminalDirection:'right',points:8}},copper_right:{label:'동접지 우측면',material:mat.copper,geometry:{kind:'ground-bar',side:'right',terminalDirection:'left',points:8}},steel_left:{label:'철접지 좌측면',material:mat.zinc,geometry:{kind:'ground-bar',side:'left',terminalDirection:'right',points:8}},steel_right:{label:'철접지 우측면',material:mat.zinc,geometry:{kind:'ground-bar',side:'right',terminalDirection:'left',points:8}}},
 cableHook:{left_tag_weld:{label:'케이블걸이 좌측면',material:mat.zinc,geometry:{kind:'tag-welded-hook',side:'left',opening:'right',welds:['start','end']}},right_tag_weld:{label:'케이블걸이 우측면',material:mat.zinc,geometry:{kind:'tag-welded-hook',side:'right',opening:'left',welds:['start','end']}},inside_horizontal_tag_weld:{label:'케이블걸이 내부 수평',material:mat.zinc,geometry:{kind:'tag-welded-hook',side:'inside',orientation:'horizontal',welds:['left-end','right-end']}}},
 cover:{four_screw:{label:'타공덮개',material:mat.steel,geometry:{kind:'cover-plate',screws:[{x:.5,y:0},{x:1,y:.5},{x:.5,y:1},{x:0,y:.5}],screwType:'phillips'}}},
 doubleLock:{exposed:{label:'노출함용 이중시건',material:mat.zinc,geometry:{kind:'through-door-eyelet',ring:'round',projectsFromDoor:true}},cover_top_center:{label:'카바용 이중시건',material:mat.zinc,geometry:{kind:'cover-tab-eyelet',position:'top-center',thinPlate:true}}}
};
function variant(type,name){const group=lib[type]||{};return group[name]||group[Object.keys(group)[0]]||null}
function describe(o){const spec=variant(o.type,o.variant||o.option);return spec?JSON.parse(JSON.stringify(spec)):null}
function list(type){return Object.entries(lib[type]||{}).map(([id,s])=>({id,...JSON.parse(JSON.stringify(s))}))}
window.KENC_OBJECT_LIBRARY={version:V,materials:mat,library:lib,variant,describe,list};
})();
